# Generated by Django 3.0.8 on 2020-07-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('username', models.CharField(default='', max_length=255)),
                ('telegram_id', models.IntegerField()),
                ('language_code', models.CharField(max_length=10)),
                ('is_bot', models.BooleanField()),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Specialization')),
            ],
        ),
        migrations.CreateModel(
            name='SpecializationStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Specialization')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Stat')),
            ],
        ),
    ]
