# Generated by Django 3.0.8 on 2020-07-12 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200711_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Stat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.User')),
            ],
        ),
    ]
