# Generated by Django 3.0.8 on 2020-07-12 09:02

from django.db import migrations

from bot.models import Stat


def seed_stat(apps, schema_editor):
    data = [
        [1, 'strength', 'Сила', 1],
        [2, 'stamina', 'Выносливость', 2],
        [3, 'agility', 'Ловкость', 3],
        [4, 'intelligence', 'Интеллект', 4]
    ]

    for stat in data:
        Stat.objects.create(
            id=stat[0],
            name=stat[1],
            title=stat[2],
            description=stat[3],
        )


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0004_userstat'),
    ]

    operations = [
        migrations.RunPython(seed_stat),
    ]


