# Generated by Django 3.0.8 on 2020-07-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_battle_monster_monsterstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='attack_speed',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='max_damage',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='min_damage',
        ),
    ]
