# Generated by Django 3.0.8 on 2020-07-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='actions',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
