# Generated by Django 3.0.8 on 2020-07-12 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20200712_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterstat',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stats', to='bot.Monster'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stats', to='bot.User'),
        ),
    ]
