# Generated by Django 3.0.8 on 2020-07-12 21:08

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20200712_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
