# Generated by Django 3.0.8 on 2020-07-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20200713_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specializationstat',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='specializationstat',
            name='stat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialization',
        ),
        migrations.AddField(
            model_name='user',
            name='energy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='unallocated_stat_points',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='SpecializationStat',
        ),
    ]
