# Generated by Django 3.0.8 on 2020-07-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20200714_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
