# Generated by Django 3.0.8 on 2020-07-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_auto_20200715_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='icon',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
