# Generated by Django 3.0.8 on 2020-07-15 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_auto_20200715_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_count', models.IntegerField()),
                ('max_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='monsterloot',
            name='loot',
        ),
        migrations.RemoveField(
            model_name='monsterloot',
            name='monster',
        ),
        migrations.RemoveField(
            model_name='userloot',
            name='loot',
        ),
        migrations.RemoveField(
            model_name='userloot',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cost',
        ),
        migrations.AddField(
            model_name='item',
            name='buy_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sale_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Loot',
        ),
        migrations.DeleteModel(
            name='MonsterLoot',
        ),
        migrations.DeleteModel(
            name='UserLoot',
        ),
        migrations.AddField(
            model_name='useritem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Item'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='bot.User'),
        ),
        migrations.AddField(
            model_name='monsteritem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='monsters', to='bot.Item'),
        ),
        migrations.AddField(
            model_name='monsteritem',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='bot.Monster'),
        ),
    ]
