# Generated by Django 3.0.8 on 2020-07-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_auto_20200715_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_shop',
            field=models.BooleanField(default=False),
        ),
    ]
