# Generated by Django 3.0.8 on 2020-07-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_item_in_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='icon',
            field=models.CharField(default='', max_length=20),
        ),
    ]
