# Generated by Django 3.0.8 on 2020-07-16 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_stat_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEquipItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equips', to='bot.User')),
            ],
        ),
    ]
