# Generated by Django 3.0.8 on 2020-07-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_userequipitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userequipitem',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
