# Generated by Django 3.0.8 on 2020-07-16 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_userequipitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userequipitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.ItemType'),
        ),
    ]
